- name: ansible jenkins job setup
  hosts: localhost
  become: yes
  tasks:
    - name: create jenkins seed-jobs-frontend
      community.general.jenkins_job:
        config: "{{ lookup('file', 'job.xml') }}"
        name: frontend
        password: sai123
        url: http://172.31.22.230:8080
        user: sai